### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Canvas android.view.Surface.lockCanvas(android.graphics.Rect)' on a null object reference

### ISSUE THREAD

**Issue by ovidiuvaro** [uxcam/flutter-plugin#11]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Canvas android.view.Surface.lockCanvas(android.graphics.Rect)' on a null object reference
       at com.uxcam.internals.gs$ad.a(SourceFile:24)
       at com.uxcam.internals.gs$ad.a(SourceFile:16)
       at com.uxcam.internals.gs$ad.$r8$lambda$6JKlk2XJVUgCouwtk1iq13kgz64()
       at com.uxcam.internals.gs$ad$$ExternalSyntheticLambda0.a(:4)
       at com.uxcam.internals.fm.a(SourceFile:51)
       at com.uxcam.internals.fm$$ExternalSyntheticLambda4.a(:2)
       at com.uxcam.internals.fm.a(SourceFile:318)
       at com.uxcam.internals.fm$$ExternalSyntheticLambda3.a(:11)
       at com.uxcam.internals.fu.a(SourceFile:54)
       at com.uxcam.internals.fu.$r8$lambda$_yzMV-E4tTqP5srseEI0KK6ea5I()
       at com.uxcam.internals.fu$$ExternalSyntheticLambda5.run(:10)
       at android.os.Handler.handleCallback(Handler.java:900)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8668)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

  **flutter_uxcam: ^2.1.2**

**Comment by ovidiuvaro** [comment]
I saw exactly the same issue on React, did anyone find the reason for this? Is it fixed?

**Comment by Anup-UXCam** [comment]
Hi, please mention the version of library where you experienced this issue.
Please upgrade to the latest version and let us know if the issue persists. Closing this as we had fixed this issue in the latest versions. Thanks for reporting the issue.
