### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by elizaveta-seleznyova-idf** [uxcam/flutter-plugin#41]
Hello UXCam developers! 

Let me introduce my problem:

com.uxcam.internals.ex.a
java.lang.OutOfMemoryError

Please help me understand what went wrong

flutter_uxcam: 2.4.2
Flutter 3.10.6
Tools • Dart 3.0.6 • DevTools 2.23.1
Brand:LGE
Model:LG K10 (2017)
Version:Android 8.1.0

Logs: 
Fatal Exception: java.lang.OutOfMemoryError:
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:1026)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:980)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:930)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:891)
       at com.uxcam.internals.ex.a(SourceFile:10)
       at com.uxcam.internals.gi$ac.a(SourceFile:27)
       at com.uxcam.internals.gi$ac.run(SourceFile:13)

**Comment by gabrieluxcam** [comment]
Hello @elizaveta-seleznyova-idf this should be resolved on 2.4.6 of the UXCam package, would it be possible to test and monitor it? Thanks

**Comment by ahmed-osama-saad** [comment]
I'm getting a similar issue, with a few of my devices runing uxcam. I'm using version 2.4.7

`Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 134217744 byte allocation with 25165824 free bytes and 122MB until OOM, target footprint 97961808, growth limit 201326592
       at java.util.Arrays.copyOf(Arrays.java:3161)
       at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
       at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
       at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
       at com.uxcam.internals.iv.a(iv.java:86)
       at com.uxcam.internals.fu.b(fu.java:288)
       at com.uxcam.internals.fu.a(fu.java:331)
       at com.uxcam.internals.fu.a(fu.java:3)
       at com.uxcam.internals.is.a(is.java:527)
       at com.uxcam.internals.ir.onResponse(ir.java:143)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.java:60)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:920)`
