### ISSUE TITLE
Out of Memory Error when using flutter_uxcam 2.4.5

### ISSUE THREAD

**Issue by myredsocks** [uxcam/flutter-plugin#44]
**Description:**
I encountered a fatal Out of Memory error while using the `flutter_uxcam` plugin in my Flutter project. This error occurred with the following versions:

- `flutter_uxcam` version: 2.4.5
- Flutter SDK version: 3.10.6

**Error Message:**
```
atal Exception: java.lang.OutOfMemoryError: Failed to allocate a 75497480 byte allocation with 8388608 free bytes and 69MB until OOM, target footprint 204333984, growth limit 268435456
       at java.util.Arrays.copyOf(Arrays.java:3766)
       at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
       at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:449)
       at java.lang.StringBuilder.append(StringBuilder.java:137)
       at org.json.JSONStringer.close(JSONStringer.java:205)
       at org.json.JSONStringer.endArray(JSONStringer.java:153)
       at org.json.JSONArray.writeTo(JSONArray.java:618)
       at org.json.JSONStringer.value(JSONStringer.java:242)
       at org.json.JSONArray.writeTo(JSONArray.java:616)
       at org.json.JSONStringer.value(JSONStringer.java:242)
       at org.json.JSONArray.writeTo(JSONArray.java:616)
       at org.json.JSONStringer.value(JSONStringer.java:242)
       at org.json.JSONArray.writeTo(JSONArray.java:616)
       at org.json.JSONStringer.value(JSONStringer.java:242)
       at org.json.JSONObject.writeTo(JSONObject.java:734)
       at org.json.JSONStringer.value(JSONStringer.java:246)
       at org.json.JSONArray.writeTo(JSONArray.java:616)
       at org.json.JSONStringer.value(JSONStringer.java:242)
       at org.json.JSONObject.writeTo(JSONObject.java:734)
       at org.json.JSONObject.toString(JSONObject.java:702)
       at com.uxcam.internals.bm.a(bm.java:1206)
       at com.uxcam.internals.fs.a(fs.java:12)
       at com.uxcam.internals.fs.a(fs.java:18)
       at com.uxcam.internals.fj.a(fj.java:20)
       at com.uxcam.internals.gl$ac.run(gl.java:197)
```

```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 75497480 byte allocation with 8388608 free bytes and 69MB until OOM, target footprint 204333984, growth limit 268435456
       at java.util.Arrays.copyOf(Arrays.java:3766)
       at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
       at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:449)
       at java.lang.StringBuilder.append(StringBuilder.java:137)
       at org.json.JSONStringer.close(JSONStringer.java:205)
       at org.json.JSONStringer.endArray(JSONStringer.java:153)
       at org.json.JSONArray.writeTo(JSONArray.java:618)
       at org.json.JSONStringer.value(JSONStringer.java:242)
       at org.json.JSONArray.writeTo(JSONArray.java:616)
       at org.json.JSONStringer.value(JSONStringer.java:242)
       at org.json.JSONArray.writeTo(JSONArray.java:616)
       at org.json.JSONStringer.value(JSONStringer.java:242)
       at org.json.JSONArray.writeTo(JSONArray.java:616)
       at org.json.JSONStringer.value(JSONStringer.java:242)
       at org.json.JSONObject.writeTo(JSONObject.java:734)
       at org.json.JSONStringer.value(JSONStringer.java:246)
       at org.json.JSONArray.writeTo(JSONArray.java:616)
       at org.json.JSONStringer.value(JSONStringer.java:242)
       at org.json.JSONObject.writeTo(JSONObject.java:734)
       at org.json.JSONObject.toString(JSONObject.java:702)
       at com.uxcam.internals.bm.a(bm.java:1206)
       at com.uxcam.internals.fs.a(fs.java:12)
       at com.uxcam.internals.fs.a(fs.java:18)
       at com.uxcam.internals.fj.a(fj.java:20)
       at com.uxcam.internals.gl$ac.run(gl.java:197)

```

**Additional Information:**
- The issue occurs consistently with the specified versions.
- Please provide guidance or updates on how to resolve this Out of Memory error when using the `flutter_uxcam` plugin.

In Crashlytics, we have observed the Out of Memory error reported on the following devices and Android versions:

Moto E5 Play
Pixel 5
Galaxy S22 Ultra
Moto G Stylus 5G
Moto G 5G (2022)
Galaxy Note20 Ultra 5G
These devices running Android 13 primarily experience this issue. This information can help in pinpointing the problem and providing a more targeted solution.

Thank you for your attention to this issue.

**Comment by DFDIEGOH** [comment]
Hi @aovooyov Diego here from UXCam, First of all, I apologize for the delay in this response. 

In the other hand, I wanted to give you good news, We have implemented a fixed for this specific crash which will be available in the upcoming release of the flutter_uxcam package. 

Will keep you updated, but please keep an eye at [this](https://developer.uxcam.com/docs/changelog) page for upcoming releases of our package
